#!/bin/bash

function json_error() {
  printf '{"error": { message: "%s","code": "%s"}}\n' "$1" "$2"
}

echo "Content-type: application/json"
echo ""

## Extract query strings.
saveIFS=$IFS
IFS='=&'
parm=($QUERY_STRING)
IFS=$saveIFS
for ((i=0; i<${#parm[@]}; i+=2))
do
    declare var_${parm[i]}=${parm[i+1]}
done

if [ -z $var_a] && [ -z $var_b] && [ -z $var_c ]; then
    json_error "Empty operands" 1
    exit 0
fi

